### ISSUE TITLE
Umbraco 7.5

### ISSUE THREAD

**Issue by rodes74** [skttl/skttl.HtmlEditor#1]
Hi Søren,

Do you intend to make a version compatible with older versions of umbraco.
I tried to install in Umbraco 7.5 but doesn't work.

After tried to install gives an error and the umbraco backoffice stopped to work. 
Have to remove the plugin from the app_plugins folder and delete the dll to start working

Best Regards,
Rodrigo

**Comment by skttl** [comment]
No, the package is dependant on a directive added in Umbraco 7.6, so that will be the minimum requirement.

There is a package called Kraftvaerk.SimpleCodeEditor, that does pretty much the same, and works in earlier versions.
